import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { palette, numbered } from "./palette";

const root = resolve(import.meta.dir, "../..");

// ---------------------------------------------------------------------------
// colors.txt — human-readable reference
// ---------------------------------------------------------------------------

function generateColorsTxt(): string {
  const p = palette;
  const lines = [
    `bg ${p.bg.slice(1)}`,
    `bg-alt ${p.bgAlt.slice(1)}`,
    `base0 ${p.bgAlt.slice(1)}`,
    `base1 ${p.red.slice(1)}`,
    `base2 ${p.sage.slice(1)}`,
    `base3 ${p.yellow.slice(1)}`,
    `base4 ${p.steel.slice(1)}`,
    `base5 ${p.magenta.slice(1)}`,
    `base6 ${p.cyan.slice(1)}`,
    `base7 ${p.white.slice(1)}`,
    `base8 ${p.muted.slice(1)}`,
    `fg ${p.fg.slice(1)}`,
    `fg-alt ${p.fgAlt.slice(1)}`,
    `grey ${p.muted.slice(1)}`,
    `red ${p.red.slice(1)}`,
    `orange ${p.orange.slice(1)}`,
    `green ${p.sage.slice(1)}`,
    `teal ${p.deepTeal.slice(1)}`,
    `yellow ${p.yellow.slice(1)}`,
    `blue ${p.steel.slice(1)}`,
    `dark-blue ${p.darkBlue.slice(1)}`,
    `magenta ${p.magenta.slice(1)}`,
    `violet ${p.magenta.slice(1)}`,
    `cyan ${p.khaki.slice(1)}`,
    `dark-cyan ${p.deepTeal.slice(1)}`,
  ];
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Neovim — lua/stilla/colors.lua
// ---------------------------------------------------------------------------

function generateNvimColors(): string {
  const n = numbered;
  return `-- Generated by packages/colors/src/generate.ts — do not edit manually.
local stilla = (vim.o.background == "dark")
\t\tand {
\t\t\t--16 colors
\t\t\tstilla0_gui = "${n.color0}", -- background
\t\t\tstilla1_gui = "${n.color1}", -- normal black
\t\t\tstilla2_gui = "${n.color2}", -- surface
\t\t\tstilla3_gui = "${n.color3}", -- muted
\t\t\tstilla3_gui_bright = "${n.color3_bright}", -- comments
\t\t\tstilla4_gui = "${n.color4}", -- foreground
\t\t\tstilla5_gui = "${n.color5}", -- white
\t\t\tstilla6_gui = "${n.color6}", -- warm white
\t\t\tstilla7_gui = "${n.color7}", -- teal
\t\t\tstilla8_gui = "${n.color8}", -- cyan
\t\t\tstilla9_gui = "${n.color9}", -- steel
\t\t\tstilla10_gui = "${n.color10}", -- navy
\t\t\tstilla11_gui = "${n.color11}", -- red
\t\t\tstilla12_gui = "${n.color12}", -- orange
\t\t\tstilla13_gui = "${n.color13}", -- yellow
\t\t\tstilla14_gui = "${n.color14}", -- sage
\t\t\tstilla15_gui = "${n.color15}", -- magenta
\t\t\tnone = "NONE",
\t\t}
\tor { -- note: light theme is still identical to nord
\t\t\t-- has not been designed or curated yet
\t\t\t--16 colors
\t\t\tstilla0_gui = "#ECEFF4", -- nord6 in palette
\t\t\tstilla1_gui = "#E5E9F0", -- nord5 in palette
\t\t\tstilla2_gui = "#D8DEE9", -- nord4 in palette
\t\t\tstilla3_gui = "#4C566A", -- nord3 in palette
\t\t\tstilla3_gui_bright = "#AEC7DF", -- out of palette
\t\t\tstilla4_gui = "#434C5E", -- nord2 in palette
\t\t\tstilla5_gui = "#3B4252", -- nord1 in palette
\t\t\tstilla6_gui = "#2E3440", -- nord0 in palette
\t\t\tstilla7_gui = "#8FBCBB", -- nord7 in palette
\t\t\tstilla8_gui = "#88C0D0", -- nord8 in palette
\t\t\tstilla9_gui = "#81A1C1", -- nord9 in palette
\t\t\tstilla10_gui = "#5E81AC", -- nord10 in palette
\t\t\tstilla11_gui = "#BF616A", -- nord11 in palette
\t\t\tstilla12_gui = "#D08770", -- nord12 in palette
\t\t\tstilla13_gui = "#EBCB8B", -- nord13 in palette
\t\t\tstilla14_gui = "#A3BE8C", -- nord14 in palette
\t\t\tstilla15_gui = "#B48EAD", -- nord15 in palette
\t\t\tnone = "NONE",
\t}

-- Enable contrast sidebars, floating windows and popup menus
if vim.g.stilla_contrast == true then
\tstilla.sidebar = stilla.stilla1_gui
\tstilla.float = stilla.stilla1_gui
else
\tstilla.sidebar = stilla.stilla0_gui
\tstilla.float = stilla.stilla0_gui
end

if vim.g.stilla_cursorline_transparent == true then
\tstilla.cursorlinefg = stilla.stilla0_gui
else
\tstilla.cursorlinefg = stilla.stilla1_gui
end

return stilla
`;
}

// ---------------------------------------------------------------------------
// Emacs — doom-stilla-theme.el
// ---------------------------------------------------------------------------

function generateEmacsTheme(): string {
  const p = palette;
  return `;;; doom-stilla-theme.el --- custom theme by jakeisnt -*- lexical-binding: t; no-byte-compile: t; -*-
;;
;; Added: January 10, 2023
;; Author: jakeisnt <https://github.com/jakeisnt>
;; Maintainer:
;; Source: https://github.com/stilla-theme
;;
;;; Commentary:
;;; Code:

;; Generated by packages/colors/src/generate.ts — do not edit color values manually.
;; Edit packages/colors/src/palette.ts, then run: bun run build

(require 'doom-themes)


;;
;;; Variables

(defgroup doom-stilla-theme nil
  "Options for the \`stilla' theme."
  :group 'doom-themes)

(defcustom doom-stilla-padded-modeline doom-themes-padded-modeline
  "If non-nil, adds a 4px padding to the mode-line.
Can be an integer to determine the exact padding."
  :group 'doom-stilla-theme
  :type '(choice integer boolean))


;;
;;; Theme definition

(def-doom-theme doom-stilla
  "Stilla minimal theme"

  ;; name        default   256       16
  ((bg         '("${p.bg}" nil       nil))
   (bg-alt     '("${p.bgAlt}" nil       nil))
   (base0      '("${p.bgAlt}" "black"   "black"))
   (base1      '("${p.red}" "#262626" "brightblack"))
   (base2      '("${p.sage}" "#303030" "brightblack"))
   (base3      '("${p.yellow}" "#3A3A3A" "brightblack"))
   (base4      '("${p.steel}" "#444444" "brightblack"))
   (base5      '("${p.magenta}" "#585858" "brightblack"))
   (base6      '("${p.cyan}" "#626262" "brightblack"))
   (base7      '("${p.white}" "#767676" "brightblack"))
   (base8      '("${p.muted}" "#a8a8a8" "white"))
   (fg         '("${p.fg}" "#e4e4e4" "brightwhite"))
   (fg-alt     '("${p.fgAlt}" "#bcbcbc" "white"))

   (grey '("${p.muted}" nil nil))

   (red         '("${p.red}" "#ff0000" "red"))
   (orange      '("${p.orange}" "#ff5f00" "brightred"))
   (green       '("${p.sage}" "#afff00" "green"))
   (teal        '("${p.deepTeal}" "#00d7af" "brightgreen"))
   (yellow      '("${p.yellow}" "#ffd700" "brightyellow"))
   (blue        '("${p.steel}" "#5fafff" "brightblue"))
   (dark-blue   '("${p.darkBlue}" "#d7ffff" "blue"))
   (magenta     '("${p.magenta}" "#d787d7" "brightmagenta"))
   (violet      '("${p.magenta}" "#d787af" "magenta"))
   (cyan        '("${p.khaki}" "#5fd7ff" "brightcyan"))
   (dark-cyan   '("${p.deepTeal}" "#00d7af" "cyan"))

   ;; face categories -- required for all themes
   (highlight      magenta)
   (vertical-bar   base2)
   (selection       base4)
   (builtin        blue)
   (comments       base6)
   (doc-comments   base6)
   (constants      orange)
   (functions      blue)
   (keywords       cyan)
   (methods        blue)
   (operators      cyan)
   (type           magenta)
   (strings        green)
   (variables      yellow)
   (numbers        orange)
   (region         base3)
   (error          red)
   (warning        yellow)
   (success        green)
   (vc-modified    blue)
   (vc-added       green)
   (vc-deleted     red)

   ;; custom categories
   (modeline-bg     base2)
   (modeline-bg-alt (doom-darken bg 0.01))
   (modeline-fg     base8)
   (modeline-fg-alt comments)

   (-modeline-pad
    (when doom-stilla-padded-modeline
      (if (integerp doom-stilla-padded-modeline) doom-stilla-padded-modeline 4))))

;;;; Base theme face overrides
  (;;;; emacs
   (lazy-highlight :background (doom-darken green 0.5) :foreground green :weight 'bold)
   (minibuffer-prompt :foreground yellow)
   (region :background (doom-darken dark-cyan 0.5) :foreground dark-cyan :distant-foreground (doom-darken fg 0.2) :extend t)
   (hl-line :background base2 :foreground nil)
   (mode-line
    :background modeline-bg :foreground modeline-fg
    :box (if -modeline-pad \`(:line-width ,-modeline-pad :color ,modeline-bg)))
   (mode-line-inactive
    :background modeline-bg-alt :foreground modeline-fg-alt
    :box (if -modeline-pad \`(:line-width ,-modeline-pad :color ,modeline-bg-alt)))
   (tooltip :background (doom-darken bg-alt 0.2) :foreground fg)
   (cursor :background yellow)
   (line-number-current-line
    :inherit '(hl-line default)
    :foreground cyan :distant-foreground nil
    :weight 'normal :italic nil :underline nil :strike-through nil)
   (completions-first-difference :foreground yellow)
   (icomplete-first-match :foreground green :underline t :weight 'bold)

;;;; doom-modeline
   (doom-modeline-buffer-path       :foreground green :weight 'bold)
   (doom-modeline-buffer-major-mode :inherit 'doom-modeline-buffer-path)
;;;; highlight-thing highlight-symbol
   (highlight-symbol-face :background region :distant-foreground fg-alt)
;;;; highlight-thing
   (highlight-thing :background region :distant-foreground fg-alt)
;;;; man <built-in>
   (Man-overstrike :inherit 'bold :foreground magenta)
   (Man-underline :inherit 'underline :foreground blue)
;;;; org <built-in>
   ((org-block &override) :background base2)
   ((org-block-background &override) :background base2)
   ((org-block-begin-line &override) :background base2)
;;;; css-mode <built-in> / scss-mode
   (css-proprietary-property :foreground orange)
   (css-property             :foreground green)
   (css-selector             :foreground blue)
;;;; dired-k
   (dired-k-commited :foreground base4)
   (dired-k-modified :foreground vc-modified)
   (dired-k-ignored :foreground cyan)
   (dired-k-added    :foreground vc-added)
;;;; ivy
   (ivy-current-match :background base3)
   (ivy-minibuffer-match-face-2
    :inherit 'ivy-minibuffer-match-face-1
    :foreground dark-cyan :background base1 :weight 'semi-bold)
;;;; js2-mode
   (js2-jsdoc-tag              :foreground magenta)
   (js2-object-property        :foreground yellow)
   (js2-object-property-access :foreground cyan)
   (js2-function-param         :foreground violet)
   (js2-jsdoc-type             :foreground base8)
   (js2-jsdoc-value            :foreground cyan)
;;;; lsp
   (lsp-headerline-breadcrumb-symbols-face :foreground base7)
;;;; rainbow-delimiters
   (rainbow-delimiters-depth-1-face :foreground magenta)
   (rainbow-delimiters-depth-2-face :foreground orange)
   (rainbow-delimiters-depth-3-face :foreground green)
   (rainbow-delimiters-depth-4-face :foreground cyan)
   (rainbow-delimiters-depth-5-face :foreground violet)
   (rainbow-delimiters-depth-6-face :foreground yellow)
   (rainbow-delimiters-depth-7-face :foreground blue)
   (rainbow-delimiters-depth-8-face :foreground teal)
   (rainbow-delimiters-depth-9-face :foreground dark-cyan)
;;;; rjsx-mode
   (rjsx-tag :foreground red)
   (rjsx-attr :foreground yellow :slant 'italic :weight 'medium)
   (rjsx-tag-bracket-face :foreground cyan)
;;;; Magit
   (magit-header-line :background (doom-lighten modeline-bg 0.2) :foreground green :weight 'bold
                      :box \`(:line-width 3 :color ,(doom-lighten modeline-bg 0.2)))
;;;; Treemacs
   (treemacs-git-modified-face :foreground vc-modified)
;;;; Web Mode
   (web-mode-html-tag-face :foreground red)
   (web-mode-html-attr-equal-face :foreground cyan)
;;;; Org Mode
   (org-level-1 :foreground green)
   (org-level-2 :foreground yellow)
   (org-level-3 :foreground red)
   (org-level-4 :foreground cyan)
   (org-level-5 :foreground blue)
   (org-level-6 :foreground magenta)
   (org-level-7 :foreground teal)
   (org-level-8 :foreground violet)
   (org-todo :foreground orange)
;;;; css
   (css-property :foreground orange)
   (css-proprietary-property :foreground magenta)
   (css-selector :foreground yellow)))

;;; doom-stilla-theme.el ends here
`;
}

// ---------------------------------------------------------------------------
// Site — CSS custom properties for Tailwind
// ---------------------------------------------------------------------------

function generateSiteColors(): string {
  const p = palette;
  return `/* Generated by packages/colors/src/generate.ts — do not edit manually. */
/* Edit packages/colors/src/palette.ts, then run: bun run build */

@theme inline {
  --color-stilla-bg: ${p.bg};
  --color-stilla-bg-alt: ${p.bgAlt};
  --color-stilla-surface: ${p.surface};
  --color-stilla-muted: ${p.muted};
  --color-stilla-comment: ${p.comment};
  --color-stilla-fg: ${p.fg};
  --color-stilla-white: ${p.white};
  --color-stilla-warm-white: ${p.warmWhite};
  --color-stilla-teal: ${p.teal};
  --color-stilla-cyan: ${p.cyan};
  --color-stilla-steel: ${p.steel};
  --color-stilla-navy: ${p.navy};
  --color-stilla-red: ${p.red};
  --color-stilla-orange: ${p.orange};
  --color-stilla-yellow: ${p.yellow};
  --color-stilla-sage: ${p.sage};
  --color-stilla-magenta: ${p.magenta};
  --color-stilla-fg-alt: ${p.fgAlt};
  --color-stilla-deep-teal: ${p.deepTeal};
  --color-stilla-dark-blue: ${p.darkBlue};
  --color-stilla-khaki: ${p.khaki};
}
`;
}

// ---------------------------------------------------------------------------
// Write all generated files
// ---------------------------------------------------------------------------

const files: Array<[string, string]> = [
  [resolve(root, "colors/colors.txt"), generateColorsTxt()],
  [resolve(root, "nvim/lua/stilla/colors.lua"), generateNvimColors()],
  [resolve(root, "emacs/doom-stilla-theme.el"), generateEmacsTheme()],
  [resolve(root, "site/src/colors.css"), generateSiteColors()],
];

for (const [path, content] of files) {
  writeFileSync(path, content);
  console.log(`wrote ${path.replace(root + "/", "")}`);
}
